name: 'Drupal module quality assurance checker'
description: 'Runs quality assurance checks against generic drupal modules'
inputs:
  module_name:
    description: 'The name of the module to test'
    required: true
  drupal_version:
    description: 'The version of drupal core to test under'
    required: true
    default: '11.x-dev'
  php_version:
    description: 'The version of php to test under'
    required: true
    default: '8.3'
  mysql_version:
    description: 'The version of mysql to test under'
    required: true
    default: '8.0'
outputs:
  results:
    description: 'QA results'
    value: ${{ steps.linting.outputs.messages}}
runs:
  using: "composite"
  steps:
    - name: Setup mysql
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: ${{ inputs.mysql_version }}
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
    - name: Setup Drupal action
      uses: bluehorndigital/setup-drupal@v1.1.0
      with:
        version: ${{ inputs.drupal_version }}
        dependencies: 'drupal/coder:^8.3'
    - name: Checkout module
      uses: actions/checkout@v4
    - name: Copy module into drupal installation
      run: mkdir -p ~/drupal/web/modules/contrib && cp -ar ~/work/${{ github.event.repository.name }} ~/drupal/web/modules/contrib
      shell: bash
    - name: Check coding standards
      run: ~/drupal/vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install,js ~/drupal/web/modules/contrib/${{ github.event.repository.name }}
      shell: bash
    - name: Run php built-in server
      run: php -S 127.0.0.1:8080 -t ~/drupal/web &
      shell: bash
    - name: Run phpunit tests
      run: cd ~/drupal/web && \export SIMPLETEST_BASE_URL="http://127.0.0.1:8080" && export SIMPLETEST_DB="mysql://root:drupal@127.0.0.1:3306/db" && export SYMFONY_DEPRECATIONS_HELPER="999999" &&  ../vendor/bin/phpunit -c core modules/contrib/${{ github.event.repository.name }}
      shell: bash
